version: '3.8'

services:
  # Banco Fonte (simulado)
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: banvic
      POSTGRES_USER: data_engineer
      POSTGRES_PASSWORD: v3rysecur&pas5w0rd
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./banvic.sql:/docker-entrypoint-initdb.d/banvic.sql
    ports:
      - 55432:5432

  # Data Warehouse (Destino)
  dw_postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: dw_banvic
      POSTGRES_USER: dw_user
      POSTGRES_PASSWORD: dw_password
    volumes:
      - ./dwdata:/var/lib/postgresql/data
    ports:
      - 5433:5432

  # Airflow - Inicialização
  airflow-init:
    image: apache/airflow:2.7.2
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db init &&
        airflow users create \
          --username admin \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com \
          --password admin
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    depends_on:
      - airflow-db
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data

  # Airflow - Banco interno
  airflow-db:
    image: postgres:16
    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    volumes:
      - ./airflow_db:/var/lib/postgresql/data

  # Airflow - Webserver
  airflow-webserver:
    image: apache/airflow:2.7.2
    restart: always
    depends_on:
      - airflow-db
      - airflow-init
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    ports:
      - 8080:8080
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
    command: webserver

  # Airflow - Scheduler
  airflow-scheduler:
    image: apache/airflow:2.7.2
    restart: always
    depends_on:
      - airflow-db
      - airflow-init
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
    command: scheduler
